apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
spec:
  selector:
    app.kubernetes.io/instance: grade-submission-api
  ports:
  - name: grade-submission-api
    protocol: TCP
    port: 3000
    targetPort: 3000
